In [1]:
#pip install fuzzywuzzy
import pandas as pd
from fuzzywuzzy import process

/home/atom/.local/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [2]:
carga = pd.read_csv("wuzy.csv")
df = pd.DataFrame(carga)
df

                mal                  bien
0              Ags.        Aguascalientes
1   Aguascalientits       Baja California
2          CampEchE   Baja California Sur
3          Coliiima              Campeche
4            ChiaPs  Coahuila de Zaragoza
5         Chiuhahua                Colima
6            duranG               Chiapas
7        Guanajauto             Chihuahua
8               NaN      Distrito Federal
9               NaN               Durango
10              NaN            Guanajuato
11              NaN              Guerrero
12              NaN               Hidalgo

In [9]:
ok = {"Mexico","Argentina","Chile","Ecuador","Colombia"}
usuario = "america mexico"
aprox = process.extractOne(usuario,ok)
aprox[1]

90

In [10]:
nombres = []
proporciones = []
def cambiosCorrectos(mal,bien):
    for filas in mal:
        x = process.extractOne(filas,bien)
        nombres.append(x[0])
        proporciones.append(x[1])
    return nombres, proporciones

In [12]:
mal = df["mal"].dropna().values
bien = df["bien"].dropna().values

In [13]:
corregido, rango = cambiosCorrectos(mal, bien)
df["correccion"]=pd.Series(corregido)
df["ration"]=pd.Series(rango)
df

                mal                  bien      correccion  ration
0              Ags.        Aguascalientes  Aguascalientes    60.0
1   Aguascalientits       Baja California  Aguascalientes    90.0
2          CampEchE   Baja California Sur        Campeche   100.0
3          Coliiima              Campeche          Colima    86.0
4            ChiaPs  Coahuila de Zaragoza         Chiapas    92.0
5         Chiuhahua                Colima       Chihuahua    89.0
6            duranG               Chiapas         Durango    92.0
7        Guanajauto             Chihuahua      Guanajuato    90.0
8               NaN      Distrito Federal             NaN     NaN
9               NaN               Durango             NaN     NaN
10              NaN            Guanajuato             NaN     NaN
11              NaN              Guerrero             NaN     NaN
12              NaN               Hidalgo             NaN     NaN