In [5]:
import pandas as pd

In [10]:
carga = pd.read_csv("datos.csv")
df = pd.DataFrame(carga)
df

,No.,Grupo,red social,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,1.0,Jw1Y-zhQURU,Instagram,NaN,Categoría,NaN,NaN,idvideo
1,NaN,NaN,NaN,NaN,Deportes,ESPN,Resumen de la Final de Wimbledon,251222
2,NaN,NaN,NaN,NaN,Gaming,PewDiePie,Minecraft: I got raided,222223
3,NaN,NaN,NaN,NaN,Vlogs,Amelia Liana,July favorites,225568
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2.0,Is-2345,Facebook,NaN,Categoría,NaN,NaN,idvideo
7,NaN,NaN,NaN,NaN,Educación,CCTMexico,Introducción a Pandas,22586
8,NaN,NaN,NaN,NaN,Comedia,Flyingkitty,Spagueth the meme,22566
9,NaN,NaN,NaN,NaN,Comedia,PewDiePie,Meme review,36999
10,NaN,NaN,NaN,NaN,Vlogs,Frannerd,How to start: Illustration,22222
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,3.0,Is-4076,Twitter,NaN,Categoría,NaN,NaN,idvideo
14,NaN,NaN,NaN,NaN,Música,Pogo,Bear and boy,993333
15,NaN,NaN,NaN,NaN,Música,Zelda soundtracks,Ocarina of time,222333
16,NaN,NaN,NaN,NaN,Comedia,Jenna Marbles,Making rammen nails,222222

In [11]:
# ARREGLADO DATOS - QUITAR ESPACIOS EN BLANCO
df = df.dropna(how="all")
df

,No.,Grupo,red social,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,1.0,Jw1Y-zhQURU,Instagram,NaN,Categoría,NaN,NaN,idvideo
1,NaN,NaN,NaN,NaN,Deportes,ESPN,Resumen de la Final de Wimbledon,251222
2,NaN,NaN,NaN,NaN,Gaming,PewDiePie,Minecraft: I got raided,222223
3,NaN,NaN,NaN,NaN,Vlogs,Amelia Liana,July favorites,225568
6,2.0,Is-2345,Facebook,NaN,Categoría,NaN,NaN,idvideo
7,NaN,NaN,NaN,NaN,Educación,CCTMexico,Introducción a Pandas,22586
8,NaN,NaN,NaN,NaN,Comedia,Flyingkitty,Spagueth the meme,22566
9,NaN,NaN,NaN,NaN,Comedia,PewDiePie,Meme review,36999
10,NaN,NaN,NaN,NaN,Vlogs,Frannerd,How to start: Illustration,22222
13,3.0,Is-4076,Twitter,NaN,Categoría,NaN,NaN,idvideo
14,NaN,NaN,NaN,NaN,Música,Pogo,Bear and boy,993333
15,NaN,NaN,NaN,NaN,Música,Zelda soundtracks,Ocarina of time,222333
16,NaN,NaN,NaN,NaN,Comedia,Jenna Marbles,Making rammen nails,222222

In [12]:
list(df)

['No.',
 'Grupo',
 'red social',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7']

In [15]:
# RELLENAR DATOS POR COLUMNAS
df["red social"]=df["red social"].fillna(method="ffill")

/tmp/ipykernel_30642/3961499905.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["red social"]=df["red social"].fillna(method="ffill")

In [16]:
df

,No.,Grupo,red social,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,1.0,Jw1Y-zhQURU,Instagram,NaN,Categoría,NaN,NaN,idvideo
1,NaN,NaN,Instagram,NaN,Deportes,ESPN,Resumen de la Final de Wimbledon,251222
2,NaN,NaN,Instagram,NaN,Gaming,PewDiePie,Minecraft: I got raided,222223
3,NaN,NaN,Instagram,NaN,Vlogs,Amelia Liana,July favorites,225568
6,2.0,Is-2345,Facebook,NaN,Categoría,NaN,NaN,idvideo
7,NaN,NaN,Facebook,NaN,Educación,CCTMexico,Introducción a Pandas,22586
8,NaN,NaN,Facebook,NaN,Comedia,Flyingkitty,Spagueth the meme,22566
9,NaN,NaN,Facebook,NaN,Comedia,PewDiePie,Meme review,36999
10,NaN,NaN,Facebook,NaN,Vlogs,Frannerd,How to start: Illustration,22222
13,3.0,Is-4076,Twitter,NaN,Categoría,NaN,NaN,idvideo
14,NaN,NaN,Twitter,NaN,Música,Pogo,Bear and boy,993333
15,NaN,NaN,Twitter,NaN,Música,Zelda soundtracks,Ocarina of time,222333
16,NaN,NaN,Twitter,NaN,Comedia,Jenna Marbles,Making rammen nails,222222

In [18]:
df["Grupo"]=df["Grupo"].ffill()
df

/tmp/ipykernel_30642/3422670727.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Grupo"]=df["Grupo"].ffill()

,No.,Grupo,red social,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,1.0,Jw1Y-zhQURU,Instagram,NaN,Categoría,NaN,NaN,idvideo
1,NaN,Jw1Y-zhQURU,Instagram,NaN,Deportes,ESPN,Resumen de la Final de Wimbledon,251222
2,NaN,Jw1Y-zhQURU,Instagram,NaN,Gaming,PewDiePie,Minecraft: I got raided,222223
3,NaN,Jw1Y-zhQURU,Instagram,NaN,Vlogs,Amelia Liana,July favorites,225568
6,2.0,Is-2345,Facebook,NaN,Categoría,NaN,NaN,idvideo
7,NaN,Is-2345,Facebook,NaN,Educación,CCTMexico,Introducción a Pandas,22586
8,NaN,Is-2345,Facebook,NaN,Comedia,Flyingkitty,Spagueth the meme,22566
9,NaN,Is-2345,Facebook,NaN,Comedia,PewDiePie,Meme review,36999
10,NaN,Is-2345,Facebook,NaN,Vlogs,Frannerd,How to start: Illustration,22222
13,3.0,Is-4076,Twitter,NaN,Categoría,NaN,NaN,idvideo
14,NaN,Is-4076,Twitter,NaN,Música,Pogo,Bear and boy,993333
15,NaN,Is-4076,Twitter,NaN,Música,Zelda soundtracks,Ocarina of time,222333
16,NaN,Is-4076,Twitter,NaN,Comedia,Jenna Marbles,Making rammen nails,222222